package com.kompressorlink.app.maintenance

import android.app.NotificationChannel
import android.app.NotificationManager
import android.app.PendingIntent
import android.content.Context
import android.content.Intent
import androidx.core.app.NotificationCompat
import androidx.core.app.NotificationManagerCompat
import androidx.work.CoroutineWorker
import androidx.work.ExistingPeriodicWorkPolicy
import androidx.work.PeriodicWorkRequestBuilder
import androidx.work.WorkManager
import androidx.work.WorkerParameters
import com.kompressorlink.app.AppContainer
import com.kompressorlink.app.KompressorLinkApp
import com.kompressorlink.app.MainActivity
import java.time.ZoneId
import java.util.concurrent.TimeUnit

// Thin shell around the pure ReminderPolicy (spec §6.4). Daily periodic
// work; also invocable on demand via the overflow menu's debug
// "Run reminder check now" (the acceptance-test hook — One UI may throttle
// periodic work [Likely], and the tab never lies regardless).
class MaintenanceCheckWorker(
    appContext: Context,
    params: WorkerParameters,
) : CoroutineWorker(appContext, params) {

    override suspend fun doWork(): Result {
        val app = applicationContext as? KompressorLinkApp ?: return Result.success()
        runCheck(app.container, applicationContext)
        return Result.success()
    }

    companion object {
        const val WORK_NAME = "kl-maintenance-check"
        const val CHANNEL_ID = "maintenance_reminders"
        const val EXTRA_START_TAB = "kl.start_tab"
        const val TAB_MAINTENANCE = "maintenance"

        suspend fun runCheck(container: AppContainer, context: Context) {
            val nowMs = System.currentTimeMillis()
            val zone = ZoneId.systemDefault()
            val anchor = container.odometerRepository.latestAnchor()
            val distance = anchor?.let { container.sessionRepository.realDistanceSince(it.epochMs) } ?: 0f
            val estimatedKm = OdometerEstimator.estimate(anchor, distance)?.km

            val decisions = container.maintenanceRepository.items().map { item ->
                ReminderPolicy.Decision(
                    item,
                    DueCalculator.evaluate(
                        item, container.maintenanceRepository.latestLogFor(item.id),
                        estimatedKm, nowMs, zone,
                    ),
                )
            }

            val manager = NotificationManagerCompat.from(context)
            for (decision in ReminderPolicy.itemsToNotify(decisions, nowMs)) {
                if (manager.areNotificationsEnabled()) {
                    val intent = Intent(context, MainActivity::class.java).apply {
                        putExtra(EXTRA_START_TAB, TAB_MAINTENANCE)
                        flags = Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_SINGLE_TOP
                    }
                    val pending = PendingIntent.getActivity(
                        context, decision.item.id.toInt(), intent,
                        PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE,
                    )
                    val text = when (decision.info.state) {
                        DueState.OVERDUE -> "${decision.item.name} is overdue"
                        else -> "${decision.item.name} is due soon"
                    }
                    val notification = NotificationCompat.Builder(context, CHANNEL_ID)
                        .setSmallIcon(android.R.drawable.ic_dialog_alert)
                        .setContentTitle("Maintenance reminder")
                        .setContentText(text)
                        .setContentIntent(pending)
                        .setAutoCancel(true)
                        .build()
                    // Tagged so a maintenance item's autogenerated Room id
                    // (e.g. the first builtin item gets id=1 on a fresh
                    // install) can never collide with another untagged
                    // notification ID elsewhere in the app — notably
                    // ConnectionService's hardcoded NOTIFICATION_ID = 1 for
                    // its foreground BLE notification.
                    manager.notify("maintenance", decision.item.id.toInt(), notification)
                }
                // Stamp even if notifications are disabled: the state was
                // surfaced as well as this device allows. This means the
                // first notification after re-enabling notifications can
                // lag up to RENOTIFY_DAYS (7 days) rather than firing
                // immediately — an intentional trade-off to avoid a burst
                // of every overdue item firing at once. The Maintenance tab
                // always shows the true due-state regardless of
                // notification delivery.
                container.maintenanceRepository.stampNotified(decision.item.id, nowMs)
            }
        }

        fun ensureChannel(context: Context) {
            val manager = context.getSystemService(NotificationManager::class.java)
            manager.createNotificationChannel(
                NotificationChannel(CHANNEL_ID, "Maintenance reminders", NotificationManager.IMPORTANCE_DEFAULT)
            )
        }

        fun schedule(context: Context) {
            WorkManager.getInstance(context).enqueueUniquePeriodicWork(
                WORK_NAME,
                ExistingPeriodicWorkPolicy.KEEP,
                PeriodicWorkRequestBuilder<MaintenanceCheckWorker>(24, TimeUnit.HOURS).build(),
            )
        }
    }
}
